#!/usr/bin/env perl -w
use IO::Uncompress::Bunzip2 qw(bunzip2 $Bunzip2Error) ;

$input = "spamlog.20101222.bz2";
$z = new IO::Uncompress::Bunzip2 $input
   or die "IO::Uncompress::Bunzip2 failed: $Bunzip2Error\n"; 

print "$input\n";
print "hello\n";
my $counter = 0;
while ( !$z->eof() ){
      $line = $z->getline();
      if ( $line =~ m/smtpfilter/ ){
	  $counter++;
	  print "$`";
	  print "$line";
	  print "$&"; 
	  print "$'";
      }
} 
print "the counter = $counter\n";
$z->close();
