#!/usr/bin/env perl -w
use IO::Uncompress::Bunzip2 qw(bunzip2 $Bunzip2Error) ;
#use IO::File;

#my $input = new IO::File "<spamlog.20101222.bz2"
#   or die "Cannot open 'spamlog.20101222.bz2':$!\n";

#my $buffer;
#bunzip2 $input => \$buffer
#	or die "bunzip2 failed: $Bunzip2Error\n";
$input = "spamlog.20101222.bz2";
$z = new IO::Uncompress::Bunzip2 $input
   or die "IO::Uncompress::Bunzip2 failed: $Bunzip2Error\n"; 

print "$input\n";
print "hello\n";
my $counter;
while ( $z ){
      $line = $z->getline();
      print $line;
} 

#$line = $z->getline();

#print "$line";