#!/usr/bin/env perl -w
use strict;
use IO::Uncompress::Bunzip2 qw(bunzip2 $Bunzip2Error);

my $input = "spamlog.20101222.bz2";
my $z = new IO::Uncompress::Bunzip2 $input
   or die "IO::Uncompress::Bunzip2 failed: $Bunzip2Error\n"; 


my $counter = 0;
my $line;
while ( !$z->eof() ){
      $line = $z->getline();
      $counter++;
#      $counter++ if $line =~ m/smtpfilter/;
#      if ($line =~ m/smtpfilter/) {
#	  $counter++;
#	  print "$' \n";
#      } 
} 
print "Counter is : $counter\n";

$z->close();
